"""fixes

Revision ID: 15179a62ee66
Revises: baa5ab8637ce
Create Date: 2024-10-17 12:10:44.257291

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '15179a62ee66'
down_revision = 'baa5ab8637ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('review', schema=None) as batch_op:
        batch_op.add_column(sa.Column('likes', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('dislikes', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('review', schema=None) as batch_op:
        batch_op.drop_column('dislikes')
        batch_op.drop_column('likes')

    # ### end Alembic commands ###
