"""btree

Revision ID: 156da75b0a65
Revises: 1d4bb3edf368
Create Date: 2024-08-07 16:02:07.053390

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '156da75b0a65'
down_revision = '1d4bb3edf368'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('foods', schema=None) as batch_op:
        batch_op.drop_index('idx_foods_title')
        batch_op.drop_index('ix_foods_category')
        batch_op.drop_index('ix_foods_title')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('foods', schema=None) as batch_op:
        batch_op.create_index('ix_foods_title', ['title'], unique=False)
        batch_op.create_index('ix_foods_category', ['category'], unique=False)
        batch_op.create_index('idx_foods_title', ['title'], unique=False)

    # ### end Alembic commands ###
