"""b-tree

Revision ID: 1d4bb3edf368
Revises: a3141515asad1
Create Date: 2024-08-07 12:14:25.207242

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '1d4bb3edf368'
down_revision = 'a3141515asad1'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('foods', schema=None) as batch_op:
        # Drop hash indexes
        batch_op.drop_index('idx_foods_category_hash', postgresql_using='hash')
        batch_op.drop_index('idx_foods_title_hash', postgresql_using='hash')

    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('foods', schema=None) as batch_op:
        # Recreate only B-tree indexes
        batch_op.create_index('idx_foods_title', ['title'], unique=False)
        batch_op.create_index('idx_foods_category', ['category'], unique=False)

    # ### end Alembic commands ###
