"""new tables

Revision ID: 35e1f15f33bd
Revises: j4828df73udfa_index
Create Date: 2024-08-12 12:43:25.518482

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '35e1f15f33bd'
down_revision = 'j4828df73udfa_index'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('first_name', sa.String(length=20), nullable=True),
    sa.Column('last_name', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('foods', schema=None) as batch_op:
        batch_op.drop_index('idx_foods_category')
        batch_op.drop_index('idx_foods_title')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('foods', schema=None) as batch_op:
        batch_op.create_index('idx_foods_title', ['title'], unique=False)
        batch_op.create_index('idx_foods_category', ['category'], unique=False)

    op.drop_table('user')
    # ### end Alembic commands ###
