"""btreet

Revision ID: 4ecf41426458
Revises: 91fc9dfbafda
Create Date: 2024-08-07 16:41:27.344571

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ecf41426458'
down_revision = '91fc9dfbafda'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('foods', schema=None) as batch_op:
        batch_op.create_index('idx_foods_title', ['title'], unique=False)
        batch_op.create_index('idx_foods_category', ['category'], unique=False)
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('foods', schema=None) as batch_op:
        batch_op.drop_index('idx_foods_title')
        batch_op.drop_index('idx_foods_category')
    # ### end Alembic commands ###