"""btreets

Revision ID: 9ac3a2e89220
Revises: 4ecf41426458
Create Date: 2024-08-07 16:47:40.575189

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9ac3a2e89220'
down_revision = '4ecf41426458'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('foods', schema=None) as batch_op:
        batch_op.drop_index('idx_foods_category')
        batch_op.drop_index('idx_foods_title')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('foods', schema=None) as batch_op:
        batch_op.create_index('idx_foods_title', ['title'], unique=False)
        batch_op.create_index('idx_foods_category', ['category'], unique=False)

    # ### end Alembic commands ###
