"""btrees

Revision ID: a102a37353fd
Revises: 156da75b0a65
Create Date: 2024-08-07 16:07:00.149761

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a102a37353fd'
down_revision = '156da75b0a65'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('foods', schema=None) as batch_op:
        batch_op.drop_index('idx_foods_category')
        batch_op.drop_index('idx_foods_title')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('foods', schema=None) as batch_op:
        batch_op.create_index('idx_foods_title', ['title'], unique=False)
        batch_op.create_index('idx_foods_category', ['category'], unique=False)

    # ### end Alembic commands ###
