from alembic import op
import sqlalchemy as sa
from sqlalchemy.sql import text

# revision identifiers, used by Alembic.
revision = 'a3141515asad1'
down_revision = 'b1d4eaedf66f'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(text('CREATE INDEX idx_foods_category_hash ON foods USING HASH (category)'))
    op.execute(text('CREATE INDEX idx_foods_title_hash ON foods USING HASH (title)'))
    # ### end Alembic commands ###
def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(text('DROP INDEX IF EXISTS idx_foods_category_hash'))
    op.execute(text('DROP INDEX IF EXISTS idx_foods_title_hash'))
    # ### end Alembic commands ###