"""index

Revision ID: b1d4eaedf66f
Revises: 39006d167be1
Create Date: 2024-08-07 11:18:31.694286

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b1d4eaedf66f'
down_revision = '39006d167be1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('foods', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_foods_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_foods_title'), ['title'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('foods', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_foods_title'))
        batch_op.drop_index(batch_op.f('ix_foods_category'))

    # ### end Alembic commands ###
