"""auth

Revision ID: c9589e485159
Revises: 
Create Date: 2024-08-23 15:14:26.095194

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c9589e485159'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('auth', schema=None) as batch_op:
        batch_op.add_column(sa.Column('token_id', sa.UUID(), nullable=True))
        batch_op.create_unique_constraint(None, ['token_id'])
        batch_op.drop_constraint('auth_user_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'token', ['token_id'], ['id'])
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('auth', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('auth_user_id_fkey', 'user', ['user_id'], ['id'])
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('token_id')

    # ### end Alembic commands ###
