from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'j4828df73udfa_index' 
down_revision = 'e2e999c065cd' 
branch_labels = None
depends_on = None

def upgrade():
  
      # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_foods_title', 'foods', ['title'], unique=False)
    op.create_index('idx_foods_category', 'foods', ['category'], unique=False)

def downgrade():
      # ### commands auto generated by Alembic - please adjust! ###
   
    op.drop_index('idx_foods_title', table_name='foods')
    op.drop_index('idx_foods_category', table_name='foods')
