openapi: 3.0.0
info:
  title: Food API
  description: API for managing food and favorite foods.
  version: "1.0.0"
paths:
  /foods:
    post:
      summary: Create a new food item
      description: |
        This endpoint allows users to create a new food item in the database.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                category:
                  type: string
                  description: The category of the food item.
                title:
                  type: string
                  description: The title or name of the food item.
                description:
                  type: string
                  description: A detailed description of the food item.
                picture:
                  type: string
                  description: The URL or path to an image of the food item.
                ingredients:
                  type: string
                  description: A list of ingredients used in the food item.
      responses:
        "201":
          description: Food created successfully
          content:
            application/json:
              example:
                id: 1
                category: "Dessert"
                title: "Chocolate Cake"
                description: "A delicious chocolate cake."
                picture: "http://example.com/image.jpg"
                ingredients: "Flour, sugar, chocolate"

  /foods/{food_id}:
    get:
      summary: Get food details
      description: |
        This endpoint allows users to retrieve details of a specific food item by its ID.
      parameters:
        - name: food_id
          in: path
          required: true
          schema:
            type: integer
          description: The unique identifier for the food item.
      responses:
        "200":
          description: Successful response with the food details.
          content:
            application/json:
              example:
                id: 1
                category: "Dessert"
                title: "Chocolate Cake"
                description: "A delicious chocolate cake."
                picture: "http://example.com/image.jpg"
                ingredients: "Flour, sugar, chocolate"
        "404":
          description: Food not found

    put:
      summary: Update food details
      description: |
        This endpoint allows users to update the details of a specific food item by its ID.
      parameters:
        - name: food_id
          in: path
          required: true
          schema:
            type: integer
          description: The unique identifier for the food item to be updated.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                category:
                  type: string
                title:
                  type: string
                description:
                  type: string
                picture:
                  type: string
                ingredients:
                  type: string
      responses:
        "200":
          description: Food updated successfully
          content:
            application/json:
              example:
                id: 1
                category: "Main Course"
                title: "Spaghetti Bolognese"
                description: "A savory pasta dish."
                picture: "http://example.com/spaghetti.jpg"
                ingredients: "Spaghetti, meat, tomato sauce"
        "404":
          description: Food not found

    delete:
      summary: Delete a food item
      description: |
        This endpoint allows users to delete a specific food item by its ID.
      parameters:
        - name: food_id
          in: path
          required: true
          schema:
            type: integer
          description: The unique identifier for the food item to be deleted.
      responses:
        "200":
          description: Food deleted successfully
        "404":
          description: Food not found
