from .options import OrmsqlalchemyOption,UserServiceOption,RequestValidatorOptions,ResponseSerialzierOption

class Development:
 ORM_SQLALCHEMY=OrmsqlalchemyOption.ORM_SQLALCHEMY
 USER_SERVICE=UserServiceOption.DEFAULT
 PYDANTIC_VALIDATOR=RequestValidatorOptions.PYDANTIC_MODEL
 RESPONSE_SERIALIZER=ResponseSerialzierOption.RESPONSE_JSON